### ISSUE TITLE
FCC installs on Python 3.14.0b4 but crashes at startup; works on Python 3.14.5

### ISSUE THREAD

**Issue by rbuenk** [Alishahryar1/free-claude-code#627]
Environment

- macOS 26.2 (Apple Silicon)
- uv 0.11.17
- free-claude-code commit: 8ae7795

Issue

I installed FCC using:

    uv tool install --python 3.14 git+https://github.com/Alishahryar1/free-claude-code.git

The tool environment was created with:

    Python 3.14.0b4

Running:

    fcc-server

failed during FastAPI/Pydantic initialization with:

    TypeError: _eval_type() got an unexpected keyword argument 'prefer_fwd_module'

After reinstalling using a stable uv-managed Python 3.14.5 interpreter, FCC started successfully.

Observations

- Fails on Python 3.14.0b4
- Works on Python 3.14.5
- Project currently specifies:

      requires-python = ">=3.14.0"

Potential improvement

Consider documenting that Python beta releases are not supported, or adding CI coverage for Python 3.14.x stable releases only.

**Comment by Alishahryar1** [comment]
You are supposed to install using the script
